### NumPy
is a core Python library for numerical computing, built for handling large arrays and matrices efficiently.

In [1]:
import numpy as np

a = [9,3,3,5]
print(np.array(a))  # Converting list into numpy array
zero = np.zeros((3,4))  # Creating a 3x4 array filled with zeros
print(zero)
one = np.ones((2,3))  # Creating a 2x3 array filled with ones
print(one)
ar = np.arange(1,10,2)  # Creating an array with values from 1 to 9 with a step of 2
print(ar)   
random_array = np.random.rand(5,3)  # Generating an array of 5 random numbers between 0 and 1
print(random_array)


[9 3 3 5]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[[0.82670408 0.12415875 0.39160026]
 [0.47845605 0.39911041 0.66373567]
 [0.76047645 0.80427451 0.20166398]
 [0.33132302 0.68629118 0.31548217]
 [0.9854203  0.0172848  0.33810306]]
